# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfd3276da458b67bb7bdd113cb92eea88c2c2e8d376108419a808b5aec7ab6fa24034236f283cb10a6acf1020193cfbd4a967149db7f8adcf39d7772a3e5fc6b

test:
  secret_key_base: 0f9796e48c84726fba171fc886f25d50333122c2cded24f6b111b0826922c7d136738101a419e8f17e33531e18821a7d11328dc128e4963e6948d632007c1213

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
